blank_issues_enabled: false
contact_links:
  - name: Discuss Table Saw on the Discord server.
    url: https://discord.gg/bWN57F5CCA
    about: Discuss bug reports, suggestions or other Table Saw related stuff on our Discord server.
